name: Deploy Spring Boot + React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download backend artifact (Spring Boot JAR)
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./email-writer-kt/target

      # Step 3: Download frontend artifact (React build)
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./email-frontend-project/dist

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=karantaragi26/karantaragi
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=karantaragi26/karantaragi
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
